FROM mysql:8.0.32

ENV MYSQL_ROOT_PASSWORD=1f18ac3cd637
ENV MYSQL_DATABASE=gym_schedule_exame
ENV MYSQL_USER=admin
ENV MYSQL_PASSWORD=1f18ac3cd637

# Copiar script de inicialização
COPY init.sql /docker-entrypoint-initdb.d/

EXPOSE 3306